name: Build and Release Port-Releaser

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Port-Releaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Build Windows binary
        run: GOOS=windows GOARCH=amd64 go build -o port-releaser-windows-amd64.exe ./

      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o port-releaser-linux-amd64 ./

      - name: Build macOS Intel binary
        run: GOOS=darwin GOARCH=amd64 go build -o port-releaser-macos-amd64 ./

      - name: Build macOS ARM64 binary
        run: GOOS=darwin GOARCH=arm64 go build -o port-releaser-macos-arm64 ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./port-releaser-windows-amd64.exe
          asset_name: port-releaser-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./port-releaser-linux-amd64
          asset_name: port-releaser-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS Intel binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./port-releaser-macos-amd64
          asset_name: port-releaser-macos-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS ARM64 binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./port-releaser-macos-arm64
          asset_name: port-releaser-macos-arm64
          asset_content_type: application/octet-stream
